### ISSUE TITLE
Automatic migration fails while installing the Tag Manager

### ISSUE THREAD

**Issue by ghost** [drummerboy46/Umbraco-Tag-Manager#2]
I tried to install tag manager on a clean Umbraco project, but the installation fails. In logs I see the following output. 
The same error occurs each time I try to manually trigger the migration.

The Tag Manager section is not visible in the Backoffice, the data type is installed.

![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/0a65be4a-9894-4b1a-ae1b-93c3d8e88389)
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/bbcea4c6-e030-4f98-950c-638e9d8bf1d5)
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/53ba0d0e-bc8b-4103-90b1-635fba3f9b7d)
![image](https://github.com/drummerboy46/Umbraco-Tag-Manager/assets/80673797/aae88b2f-a130-4383-89d7-b6d4be4f4e4c)

"Umbraco.Cms" Version="13.2.2"
"Our.Umbraco.Community.TagManager" Version="13.0.5"

```
[11:15:04 INF] Execute TagManagerMigrationHelper
[11:15:04 ERR] Exception (d665ea9d).
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "umbracoUserGroup2App": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 261
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.<>c__DisplayClass296_0.<ExecuteNonQueryHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at Our.Umbraco.Community.TagManager.Migrations.TagManagerMigrationHelper.Migrate()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigration(Type migrationType, MigrationContext context)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunScopedMigration(Type migrationType, MigrationPlan plan)
   at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)
[11:15:04 ERR] Plan failed at step UsomeTagManagerMigrationv1-db
```

**Comment by ghost** [comment]
It works on MSSQL.
